name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.3
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # http: ^1.0.0
  # dio: ^5.1.2
  flutter_local_notifications: 12.0.0
  rxdart: ^0.27.7

  # permission_handler: ^11.0.1
  package_info_plus: ^3.1.2
  # open_filex: ^4.3.2
  sensors_plus: ^3.0.2
  share_plus: ^7.0.2
  chopper: ^6.1.4
  collection: ^1.17.1

  cached_network_image: ^3.2.3
  carousel_slider: ^4.0.0
  card_slider: ^1.0.5
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  # equatable: ^2.0.5
  # flutter_inappwebview: ^5.7.2+3
  # flutter_math_fork: ^0.7.1
  # flutter_html: ^2.2.0
  # get: ^4.3.8
  # html: ^0.15.0
  # hexcolor: ^3.0.1
  # loop_page_view: ^1.2.5
  # shared_preferences: ^2.0.17
  # shimmer: ^3.0.0
  # smooth_page_indicator: ^1.1.0
  # flutter_staggered_grid_view: 0.6.2
  # timelines: ^0.1.0
  # webview_flutter: ^2.4.0

  # firebase_analytics: ^10.0.3
  # firebase_crashlytics: ^3.0.3
  # firebase_remote_config: ^4.2.3
  # firebase_core: ^2.14.0

  device_info_plus: ^9.0.0
  # izooto_plugin: 2.2.2
  # device_apps: ^2.1.1
  # url_launcher: ^6.0.3

  # scrollable_positioned_list: 0.3.8
  # photo_view: ^0.14.0

  # #hive
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  path_provider: ^2.0.0

  # share: ^2.0.4

  # # flutter_layout_grid: ^2.0.5
  # #picture in picture
  # pip_view: ^0.9.7

  # geolocator: ^10.1.0
  # geocoding: ^2.1.1
  permission_handler: ^11.0.1


dependency_overrides:
  flutter_svg: ^2.0.8

dev_dependencies:
  lint: ^2.1.2
